# Generated by Django 6.0.7 on 2026-08-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='id',
            new_name='std_id',
        ),
    ]
