# Generated by Django 6.0.7 on 2026-08-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_rename_id_students_std_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='std_id',
            new_name='id',
        ),
    ]
